Airship2 GA Announcement
AirshipWeb/airship-website pull request #153
Opened 2021-04-09 20:48 UTC by alexander-hughes

Signed-off-by: Alexander Hughes <Alexander.Hughes@pm.me>

2021-04-13 16:49 UTC, intlabs commented on src/pages/blog/airship2-released.md
> +* **Homogeneous -> Equivalency** <br> Regarding our homogenous goal, we deliver a level of uniformity in terms of how we lifecycle the clouds themselves. We also provide a mechanism to ensure these c
`our` is not appropriate here.

2021-04-13 17:14 UTC, intlabs requested changes
I'm making some changes to the google doc that this is sourced from - please can we incorporate them before merge

2021-04-13 17:50 UTC, alexander-hughes commented
> 
> 
> I'm making some changes to the google doc that this is sourced from - please can we incorporate them before merge

Certainly.  Please send me the link, or updated word doc when ready. These changes were sourced from a word doc provided by Rodolfo late last week.

2021-04-14 14:26 UTC, jtwill98 requested changes
One typo issue other wise lgtm.

2021-04-14 14:26 UTC, jtwill98 commented on src/pages/blog/airship2-released.md
> +* **Cloud Agnostic -> Any Cloud** <br> With Airship 2, we have fully embraced the cluster-api and have integrated it closely into airshipctl. We support a variety of infrastructure backends and opera
Meta3 (sp, typo)  should be Metal3

2021-04-15 11:48 UTC, alexander-hughes commented on src/pages/blog/airship2-released.md
> +* **Cloud Agnostic -> Any Cloud** <br> With Airship 2, we have fully embraced the cluster-api and have integrated it closely into airshipctl. We support a variety of infrastructure backends and opera
Thanks, resolved in latest revision.

2021-04-16 11:59 UTC, merged